export const PATH = {
  TOP: () => "/",
  ITEMS: () => "/items",
  LOGIN: () => "/login",
  SIGNUP: () => "/sign-up",
  ITEMS_ID: (id: string) => `/items/${id}`,
  CART: () => "/cart",
  CHECKOUT: () => "/checkout",
  CHECKOUT_COMPLETE: () => "/checkout/complete",
  ME: () => "/me",
  ME_ORDERS: () => "/me/orders",
  ME_ORDERS_ORDER_ID: (id: string) => `/me/orders/${id}`,
  ME_FAVORITES: () => "/me/favorites",
  CONTACT: () => "/contact",
};
