name: SonarCloud analysis

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    environment:
      name: sonarcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:coverage
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=src
            -Dsonar.exclusions=dist/,node_modules,public,src/test,**/*.spec.tsx,**/*.test.tsx
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.tsx,**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.log.level=DEBUG
          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
          projectBaseDir: .
