name: SonarCloud analysis

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    environment:
      name: sonarcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args:
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=src
            -Dsonar.exclusions=**/*.spec.tsx,**/*.test.tsx
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.tsx,**/*.test.tsx
            -Dsonar.log.level=DEBUG
          # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
          projectBaseDir: .
